export const pt = {
  layout: {
    rotate: "Gire o aparelho para jogar no celular",
  },
  common: {
    points: "Pontos",
    penalty: "Tempo",
    moves: "Jogadas",
    play: "jogar",
    prev: "anterior",
    next: "próximo",
    reward: "Você ganhou uma recompensa!",
    goToShop: "ir para a loja",
    dragonRun: "Sequência do Dragão",
    phoenixRun: "Sequência da Fênix",
    boatRun: "Sequência do Barco",
    discardAndShuffle: "Descartar e embaralhar",
    yes: "sim",
    no: "não",
    roundN: "Rodada {{round}}",
    pointsN: "{{points}} pontos",
    objective: "Objetivo",
    deck: "Baralho",
    yourDeck: "Seu baralho",
    coins: "Moedas",
    buy: "comprar",
    shop: "loja",
    close: "fechar",
    paused: "pausado",
    help: "Ajuda",
    celebrate: "Comemorar!",
  },
  intro: {
    goal: "Passe por 24 rodadas de Mahjong Solitaire para completar sua aventura!",
    difficulty:
      "Cada rodada fica um pouco mais difícil, com metas de pontos maiores e uma penalidade de tempo mais forte.",
    upgrade: "Desbloqueie novas peças e melhorias especiais ao longo do caminho.",
  },
  settings: {
    title: "Configurações",
    soundVolume: "Volume dos efeitos",
    musicVolume: "Volume da música",
    restart: "Reiniciar o jogo",
    restartRun: "Reiniciar aventura",
    newRun: "Nova aventura",
    goBack: "Voltar ao início",
  },
  material: {
    quartz: "quartzo",
    obsidian: "obsidiana",
    jade: "jade",
    emerald: "esmeralda",
    garnet: "granada",
    ruby: "rubi",
    topaz: "topázio",
    sapphire: "safira",
    bone: "marfim",
  },
  suit: {
    flower: "Flor",
    bam: "Bambu",
    crack: "Caracteres",
    dot: "Círculos",
    dragon: "Dragão",
    wind: "Vento",
    rabbit: "Coelho",
    phoenix: "Fênix",
    joker: "Coringa",
    mutation: "Mutação",
    taijitu: "Taijitu",
    element: "Elemento",
    gem: "Gema",
    frog: "Sapo",
    lotus: "Lótus",
    sparrow: "Pardal",
    shadow: "Sombra",
  },
  windDirections: {
    n: "Norte",
    s: "Sul",
    e: "Leste",
    w: "Oeste",
  },
  color: {
    r: "Vermelho",
    g: "Verde",
    b: "Azul",
    k: "Preto",
  },
  cardName: {
    mutation1: "Mutação Caracteres / Bambu",
    mutation2: "Mutação Círculos / Caracteres",
    mutation3: "Mutação Bambu / Círculos",
    wind: "Vento {{direction}}",
    dragon: "Dragão {{color}}",
    phoenix: "Fênix {{color}}",
    rabbit: "Coelho {{color}}",
    element: "Elemento {{color}}",
    shadow: "Sombra {{color}}",
    gemr: "Granada",
    gemg: "Jade",
    gemb: "Topázio",
    gemk: "Quartzo",
  },
  tutorial: {
    stages: {
      tiles: "peças",
      clearing: "remoção",
      dragons: "dragões",
      seasonsAndFlowers: "ventos e flores",
      board: "tabuleiro",
      shop: "loja",
      upgrade: "melhorias",
      materials: "materiais",
    },
    tiles1:
      "Para vencer uma rodada de <span class={{crackClass}}>Whatajong</span>, limpe todas as peças e faça pelo menos a quantidade de pontos exigida naquela rodada.",
    tiles2: "Para remover peças, combine duas peças iguais.",
    tiles3:
      "Cada peça precisa estar livre em pelo menos um dos lados, esquerdo ou direito, e não pode ter nenhuma peça sobre ela.",
    tiles4: "Ao remover um par, você ganha pontos.",
    tiles5: "2 pontos!",
    board1:
      "Os indicadores de <span class={{bamClass}}>pontos e tempo</span> mostram quantos pontos você ganhou e quantos perdeu conforme o tempo passa.",
    board2:
      "O indicador de <span class={{crackClass}}>moedas</span> mostra quantas moedas você ganhou nesta rodada.",
    board3: "Depois de cada partida, você pode gastar as moedas para comprar mais peças.",
    board4:
      "O indicador de <span class={{dotClass}}>jogadas</span> mostra quantas combinações estão disponíveis.",
    board5:
      "Se chegar a 0, o tabuleiro ficou sem solução e a rodada é perdida.",
    shop1: "Para fazer mais pontos, compre novas peças!",
    shop2:
      "Use <span class={{bamClass}}>renovar</span> para receber novos itens na loja.",
    shop3:
      "Se você gostar de algo, mas ainda não tiver moedas suficientes, <span class={{dotClass}}>congele</span> os itens até a próxima rodada.",
    material1:
      "Compre três pares de peças idênticas para uni-las em uma versão mais poderosa.",
    material: {
      b: "Você pode remover esta peça mesmo se nenhum dos lados estiver aberto.",
      g: "Estas peças dão pontos extras.",
      r: "Estas peças dão moedas.",
      k: "Remova esta peça para parar a penalidade de tempo.",
    },
  },
  mode: {
    title: "Bem-vindo à aventura!",
    subtitle: "Escolha a dificuldade",
    easy: {
      title: "Passeio tranquilo",
      tag: "fácil",
    },
    medium: {
      title: "Águas agitadas",
      tag: "médio",
    },
    hard: {
      title: "Contra o redemoinho",
      tag: "difícil",
    },
  },
  gameOver: {
    win: {
      victory: "Vitória!",
      success: "Sucesso!",
      champion: "Campeão!",
      awesome: "Incrível!",
      winner: "Vencedor!",
      glorious: "Glorioso!",
      wellPlayed: "Muito bem!",
    },
    defeat: {
      defeat: "Derrota!",
      gameOver: "Fim de jogo",
      oops: "Ops...",
      failed: "Não foi desta vez",
      crushed: "Rodada perdida!",
      wasted: "Tente novamente!",
    },
    timePenalty: "Penalidade de tempo ({{time}} s)",
    totalPoints: "Pontos totais",
    playAgain: "Jogar novamente",
    roundReward: "Recompensa da rodada",
    tileCoins: "Moedas das peças",
    overachiever: "Desempenho extra ({{percent}} %)",
    trySameRun: "Tentar novamente",
    noPairs: "Não há mais jogadas disponíveis",
    notEnoughPoints: "Você não conseguiu pontos suficientes",
  },
  shop: {
    upgrade: {
      title: "Melhoria disponível!",
      description:
        "Ao reunir 3 pares de peças idênticas, você pode transformá-las em uma versão mais forte.",
      button: "melhorar",
      easierToMatch: "mais fácil de combinar",
      morePoints: "mais pontos",
      getCoins: "ganha moedas",
    },
    deckCapacity: "capacidade do baralho:",
    newTiles: "novas peças:",
    buyTiles: "comprar peças",
  },
  tileDetails: {
    materialExtraPoints: "pontos extras de {{material}}",
    materialExplanation: {
      blue: "Remova esta peça mesmo se nenhum dos lados estiver aberto.",
      black: "Remova esta peça para parar a penalidade de tempo.",
    },
    explanation: {
      wind: "Ao ser removida, uma rajada desloca as peças na direção indicada pelo vento.",
      rabbit: "Ao remover peças de Coelho, você recebe uma moeda.",
      flower:
        "As Flores podem ser vermelhas, verdes ou azuis.<br />Qualquer Flor pode formar par com outra Flor.",
      dragon:
        "Remova peças de Dragão para iniciar uma <strong>Sequência do Dragão</strong>.<br />Enquanto ela estiver ativa, remova peças da cor do Dragão para fazer mais pontos.",
      phoenix:
        "Remova peças de Fênix para iniciar uma <strong>Sequência da Fênix</strong>.<br />Enquanto ela estiver ativa, remova números consecutivos para fazer mais pontos.",
      mutation:
        "As peças de Mutação permitem trocar o naipe das peças do tabuleiro.",
      m1: "Troca todas as peças de Caracteres (::c::) e Bambu (::b::) do tabuleiro.",
      m2: "Troca todas as peças de Círculos (::o::) e Caracteres (::c::) do tabuleiro.",
      m3: "Troca todas as peças de Bambu (::b::) e Círculos (::o::) do tabuleiro.",
      joker:
        "Remova um Coringa para embaralhar o tabuleiro.<br />Coringas combinam com qualquer cor e qualquer número.",
      element:
        "Cada peça de Elemento no tabuleiro dá pontos extras às peças da mesma cor.<br />Quando um Elemento está livre, o bônus fica ainda maior.",
      taijitu:
        "Ao ser removido, concede pontos extras se as duas peças estiverem lado a lado.",
      frog: "Combine um Sapo com uma peça livre da mesma cor; o sapo salta para a peça.",
      lotus:
        "Combine uma peça livre com um Lótus da mesma cor; a peça salta para o Lótus.",
      sparrow:
        "Combine um Pardal com qualquer peça da mesma cor para que elas troquem de posição.",
      gem: "Ao remover esta peça, o material de todas as peças da mesma cor melhora temporariamente.",
      shadow:
        "Quando uma Sombra está livre, todas as peças da mesma cor se tornam pretas.",
    },
  },
  runSelect: {
    title: "Prepare-se!",
    subtitle: "Vença a rodada atual para liberar as próximas.",
  },
  runReward: {
    title: "Novas peças!",
    subtitle: "escolha uma grátis",
    playAgain: "jogar novamente",
    win: "Você venceu!",
    noPairs: "ops! não há mais jogadas",
    noPoints: "você pode fazer mais pontos: {{points}} de {{objective}}",
    solvePuzzle: "resolver o tabuleiro",
  },
  end: {
    title: "Parabéns!",
    subtitle: "Você concluiu o jogo.",
    totalPoints: "Pontos totais",
    attempts: "Tentativas",
    difficulty: "Dificuldade",
    newAdventure: "Nova aventura",
  },
}
