export type CategoriaBiblioteca =
  | "Santos e Santas"
  | "Espiritualidade"
  | "Mariologia"
  | "Oração"
  | "Sacerdócio"
  | "Formação"

export type LivroBiblioteca = {
  id: string
  titulo: string
  subtitulo?: string
  autor: string
  categoria: CategoriaBiblioteca
  santo?: string
  paginas?: number
  edicao?: string
  periodo?: string
  descricao: string
  capa?: string
  downloadUrl: string
  fonteUrl: string
  hospedagem: "MediaFire" | "OneDrive" | "Google Drive" | "Alexandria Católica" | "Outro"
  destaque?: boolean
  downloadDireto?: boolean
}

export const livrosBiblioteca: LivroBiblioteca[] = [
  {
    id: "padre-pio-o-estigmatizado",
    titulo: "Padre Pio — O Estigmatizado",
    autor: "Maria Winowska",
    categoria: "Santos e Santas",
    santo: "São Padre Pio de Pietrelcina",
    edicao: "1956",
    periodo: "1887–1968",
    descricao: "Biografia dedicada à vida, espiritualidade e testemunho sacerdotal de São Padre Pio.",
    capa: "/images/biblioteca/padre-pio.jpg",
    downloadUrl: "https://www.mediafire.com/file/7kgi86ajakan6fi/Maria_Winowska_Padre_Pio.pdf/file",
    fonteUrl: "https://alexandriacatolica.blogspot.com/2010/11/padre-pio.html",
    hospedagem: "MediaFire",
    destaque: true,
    downloadDireto: true,
  },
  {
    id: "santa-gema-galgani-flor-da-paixao",
    titulo: "A Flor da Paixão — Santa Gema Galgani",
    autor: "Pe. Germano de Santo Estanislau",
    categoria: "Santos e Santas",
    santo: "Santa Gema Galgani",
    paginas: 464,
    edicao: "1940",
    periodo: "1878–1903",
    descricao: "Biografia extensa de Santa Gema Galgani, com destaque para sua vida de oração e união com a Paixão de Cristo.",
    capa: "/images/biblioteca/gemma-galgani.jpg",
    downloadUrl: "https://alexandriacatolica.blogspot.com/2010/11/flor-da-paixao-santa-gema-galgani-pe.html",
    fonteUrl: "https://alexandriacatolica.blogspot.com/2010/11/flor-da-paixao-santa-gema-galgani-pe.html",
    hospedagem: "Alexandria Católica",
    destaque: true,
  },
  {
    id: "santa-faustina-excertos-diario",
    titulo: "Excertos do Diário de Santa Faustina",
    autor: "Santa Faustina Kowalska",
    categoria: "Santos e Santas",
    santo: "Santa Faustina Kowalska",
    paginas: 117,
    periodo: "1905–1938",
    descricao: "Seleção de textos do Diário de Santa Faustina sobre a Misericórdia Divina, confiança em Jesus e vida espiritual.",
    capa: "/images/biblioteca/faustina.jpg",
    downloadUrl: "https://1drv.ms/b/s!Aqrn-T8uGG_GgSuHDo0hx-hgSRvK",
    fonteUrl: "https://alexandriacatolica.blogspot.com/2010/12/santa-faustina.html",
    hospedagem: "OneDrive",
    destaque: true,
    downloadDireto: true,
  },
  {
    id: "santa-rita-vida",
    titulo: "Vida de Santa Rita de Cássia",
    subtitulo: "Modelo nos diversos estados da vida cristã",
    autor: "Pe. José R. Cabezas, O.S.A.",
    categoria: "Santos e Santas",
    santo: "Santa Rita de Cássia",
    paginas: 67,
    periodo: "1381–1457",
    descricao: "Vida de Santa Rita apresentada como modelo de fidelidade cristã na juventude, matrimônio, viuvez e vida religiosa.",
    capa: "/images/biblioteca/santa-rita.jpg",
    downloadUrl: "https://1drv.ms/b/s!Aqrn-T8uGG_GgRylwGZhyyracK--?e=e9BQOg",
    fonteUrl: "https://alexandriacatolica.blogspot.com/2010/11/santa-rita-de-cassia.html",
    hospedagem: "OneDrive",
    downloadDireto: true,
  },
  {
    id: "teresinha-caminho-todo-novo",
    titulo: "Um Caminho Todo Novo",
    subtitulo: "Santa Teresinha de Lisieux",
    autor: "M. M. Philipon, O.P.",
    categoria: "Santos e Santas",
    santo: "Santa Teresinha do Menino Jesus",
    paginas: 350,
    edicao: "1954",
    descricao: "Estudo sobre a pequena via de Santa Teresinha: confiança, abandono, primado do amor e fidelidade nas pequenas coisas.",
    capa: "/images/biblioteca/teresinha.jpg",
    downloadUrl: "https://drive.google.com/file/d/0Bxu0vxnfM6FMU2dSOXA3dUNaaVk/view",
    fonteUrl: "https://alexandriacatolica.blogspot.com/2017/10/um-caminho-todo-novo.html",
    hospedagem: "Google Drive",
    destaque: true,
    downloadDireto: true,
  },
  {
    id: "cura-dars-francis-trochu",
    titulo: "O Santo Cura D'Ars",
    autor: "Francis Trochu",
    categoria: "Santos e Santas",
    santo: "São João Maria Vianney",
    paginas: 415,
    edicao: "1997",
    periodo: "1786–1859",
    descricao: "Biografia clássica de São João Maria Vianney, destacando sua vida sacerdotal, oração, penitência e zelo pelas almas.",
    capa: "/images/biblioteca/cura-dars.jpg",
    downloadUrl: "https://1drv.ms/b/s!Aqrn-T8uGG_GgVd0h5XDcHXS_3M5",
    fonteUrl: "https://alexandriacatolica.blogspot.com/2011/01/1786-1818-sao-joao-maria-batista.html",
    hospedagem: "OneDrive",
    destaque: true,
    downloadDireto: true,
  },
  {
    id: "inacio-autobiografia",
    titulo: "Autobiografia de Santo Inácio de Loyola",
    autor: "Santo Inácio de Loyola",
    categoria: "Santos e Santas",
    santo: "Santo Inácio de Loyola",
    paginas: 152,
    edicao: "2005",
    descricao: "Relato autobiográfico preservando a memória de sua conversão, peregrinação e discernimento espiritual.",
    capa: "/images/biblioteca/santo-inacio.jpg",
    downloadUrl: "https://1drv.ms/b/s!Aqrn-T8uGG_GgUpjZkr5gwt7k6Qe",
    fonteUrl: "https://alexandriacatolica.blogspot.com/2011/01/santo-inacio-de-loyola-autobiografia.html",
    hospedagem: "OneDrive",
    downloadDireto: true,
  },
  {
    id: "santa-monica",
    titulo: "Santa Mônica",
    subtitulo: "Mãe de Santo Agostinho",
    autor: "A. Brugnuolo",
    categoria: "Santos e Santas",
    santo: "Santa Mônica",
    paginas: 93,
    edicao: "1950",
    periodo: "331–387",
    descricao: "Biografia de Santa Mônica centrada em sua perseverança na oração e dedicação pela conversão de Santo Agostinho.",
    capa: "/images/biblioteca/santa-monica.jpg",
    downloadUrl: "https://1drv.ms/b/s!Aqrn-T8uGG_GiGhu8U5N10Jpk5Rk",
    fonteUrl: "https://alexandriacatolica.blogspot.com/2011/08/27-de-agosto-santa-monica.html",
    hospedagem: "OneDrive",
    downloadDireto: true,
  },
  {
    id: "santa-rosa-lima-anjo-andes",
    titulo: "O Anjo dos Andes",
    subtitulo: "Santa Rosa de Lima",
    autor: "Mary Fabyan Windeatt",
    categoria: "Santos e Santas",
    santo: "Santa Rosa de Lima",
    paginas: 59,
    periodo: "1586–1617",
    descricao: "Biografia acessível sobre Santa Rosa de Lima e sua entrega total a Deus desde a juventude.",
    capa: "/images/biblioteca/santa-rosa.jpg",
    downloadUrl: "https://1drv.ms/b/s!Aqrn-T8uGG_GgR0xfitY4T_V6n-b?e=ciIXvX",
    fonteUrl: "https://alexandriacatolica.blogspot.com/2010/11/santa-rosa-de-lima.html",
    hospedagem: "OneDrive",
    downloadDireto: true,
  },
  {
    id: "confissoes-agostinho",
    titulo: "Confissões",
    autor: "Santo Agostinho",
    categoria: "Santos e Santas",
    santo: "Santo Agostinho",
    descricao: "Obra autobiográfica e espiritual em que Santo Agostinho narra sua conversão e louva a ação da graça de Deus.",
    capa: "/images/biblioteca/confissoes-agostinho.jpg",
    downloadUrl: "https://alexandriacatolica.blogspot.com/search?q=Confiss%C3%B5es+Santo+Agostinho",
    fonteUrl: "https://alexandriacatolica.blogspot.com/search?q=Confiss%C3%B5es+Santo+Agostinho",
    hospedagem: "Alexandria Católica",
  },
  {
    id: "historia-de-uma-alma",
    titulo: "História de uma Alma",
    autor: "Santa Teresinha do Menino Jesus",
    categoria: "Santos e Santas",
    santo: "Santa Teresinha do Menino Jesus",
    descricao: "Autobiografia espiritual de Santa Teresinha, fonte privilegiada de sua pequena via de confiança e amor.",
    capa: "/images/biblioteca/historia-de-uma-alma.jpg",
    downloadUrl: "https://alexandriacatolica.blogspot.com/search?q=Hist%C3%B3ria+de+uma+Alma",
    fonteUrl: "https://alexandriacatolica.blogspot.com/search?q=Hist%C3%B3ria+de+uma+Alma",
    hospedagem: "Alexandria Católica",
  },
  {
    id: "tratado-do-purgatorio",
    titulo: "Tratado do Purgatório",
    autor: "Santa Catarina de Gênova",
    categoria: "Santos e Santas",
    santo: "Santa Catarina de Gênova",
    descricao: "Pequeno clássico espiritual sobre purificação da alma, misericórdia divina e esperança cristã.",
    capa: "/images/biblioteca/tratado-purgatorio.jpg",
    downloadUrl: "https://alexandriacatolica.blogspot.com/search?q=Tratado+do+Purgat%C3%B3rio",
    fonteUrl: "https://alexandriacatolica.blogspot.com/search?q=Tratado+do+Purgat%C3%B3rio",
    hospedagem: "Alexandria Católica",
  },
  {
    id: "filoteia",
    titulo: "Filoteia ou Introdução à Vida Devota",
    autor: "São Francisco de Sales",
    categoria: "Espiritualidade",
    santo: "São Francisco de Sales",
    descricao: "Clássico da espiritualidade cristã sobre vida devota, oração, virtudes e santificação nas circunstâncias ordinárias.",
    capa: "/images/biblioteca/francisco-sales.jpg",
    downloadUrl: "https://alexandriacatolica.blogspot.com/2010/12/filoteia.html",
    fonteUrl: "https://alexandriacatolica.blogspot.com/2010/12/filoteia.html",
    hospedagem: "Alexandria Católica",
    destaque: true,
  },
  {
    id: "glorias-de-maria",
    titulo: "Glórias de Maria",
    autor: "Santo Afonso Maria de Ligório",
    categoria: "Mariologia",
    paginas: 337,
    edicao: "1989",
    descricao: "Obra clássica de devoção mariana de Santo Afonso Maria de Ligório.",
    capa: "/images/biblioteca/glorias-de-maria.jpg",
    downloadUrl: "https://alexandriacatolica.blogspot.com/2020/07/um-classico-da-devocao-mariana.html",
    fonteUrl: "https://alexandriacatolica.blogspot.com/2020/07/um-classico-da-devocao-mariana.html",
    hospedagem: "Alexandria Católica",
    destaque: true,
  },
  {
    id: "tratado-verdadeira-devocao",
    titulo: "Tratado da Verdadeira Devoção à Santíssima Virgem Maria",
    autor: "São Luís Maria Grignion de Montfort",
    categoria: "Mariologia",
    paginas: 320,
    edicao: "1943",
    descricao: "Tratado mariano sobre a consagração a Jesus por Maria e a verdadeira devoção à Santíssima Virgem.",
    capa: "/images/biblioteca/tratado-verdadeira-devocao.jpg",
    downloadUrl: "https://alexandriacatolica.blogspot.com/2020/08/consagra-te-agora-com-edicao-de-1943.html",
    fonteUrl: "https://alexandriacatolica.blogspot.com/2020/08/consagra-te-agora-com-edicao-de-1943.html",
    hospedagem: "Alexandria Católica",
    destaque: true,
  },
  {
    id: "segredo-verdadeira-devocao",
    titulo: "O Segredo da Verdadeira Devoção",
    autor: "Pe. Júlio Maria de Lombaerde, S.D.N.",
    categoria: "Mariologia",
    paginas: 288,
    edicao: "1961",
    descricao: "Comentário espiritual da doutrina de São Luís Maria de Montfort, destinado às almas que desejam crescer na santidade.",
    capa: "/images/biblioteca/segredo-verdadeira-devocao.jpg",
    downloadUrl: "https://alexandriacatolica.blogspot.com/2011/05/fonte-o-segredo-da-verdadeira-devocao.html",
    fonteUrl: "https://alexandriacatolica.blogspot.com/2011/05/fonte-o-segredo-da-verdadeira-devocao.html",
    hospedagem: "Alexandria Católica",
  },
  {
    id: "a-selva",
    titulo: "A Selva",
    autor: "Santo Afonso Maria de Ligório",
    categoria: "Sacerdócio",
    paginas: 138,
    edicao: "2002",
    descricao: "Obra destinada especialmente a ordinandos e sacerdotes, com ensinamentos sobre dignidade, deveres e vida sacerdotal.",
    capa: "/images/biblioteca/a-selva.jpg",
    downloadUrl: "https://alexandriacatolica.blogspot.com/2010/12/selva.html",
    fonteUrl: "https://alexandriacatolica.blogspot.com/2010/12/selva.html",
    hospedagem: "Alexandria Católica",
  },
  {
    id: "exercicios-espirituais-inacio",
    titulo: "Exercícios Espirituais",
    autor: "Santo Inácio de Loyola",
    categoria: "Espiritualidade",
    santo: "Santo Inácio de Loyola",
    capa: "/images/biblioteca/exercicios-espirituais.jpg",
    descricao: "Texto clássico sobre exame de consciência, meditação, contemplação e discernimento espiritual.",
    downloadUrl: "https://alexandriacatolica.blogspot.com/2010/11/exercicios-espirituais-de-santo-inacio.html",
    fonteUrl: "https://alexandriacatolica.blogspot.com/2010/11/exercicios-espirituais-de-santo-inacio.html",
    hospedagem: "Alexandria Católica",
  },
  {
    id: "o-grande-meio-oracao",
    titulo: "A Oração — O Grande Meio da Salvação",
    autor: "Santo Afonso Maria de Ligório",
    categoria: "Oração",
    descricao: "Tratado sobre a necessidade, eficácia e condições da oração para alcançar a salvação e as graças de Deus.",
    capa: "/images/biblioteca/grande-meio-oracao.jpg",
    downloadUrl: "https://alexandriacatolica.blogspot.com/2011/02/oracao-santo-afonso-maria-de-ligorio.html",
    fonteUrl: "https://alexandriacatolica.blogspot.com/2011/02/oracao-santo-afonso-maria-de-ligorio.html",
    hospedagem: "Alexandria Católica",
  },
  {
    id: "meditacoes-santo-afonso",
    titulo: "Meditações para Todos os Dias e Festas do Ano",
    subtitulo: "Coleção em três tomos",
    autor: "Santo Afonso Maria de Ligório / P. Thiago Maria Cristini",
    categoria: "Espiritualidade",
    paginas: 1379,
    edicao: "1921–1922",
    descricao: "Coleção de meditações distribuídas ao longo do ano eclesiástico em três tomos.",
    capa: "/images/biblioteca/meditacoes-santo-afonso.jpg",
    downloadUrl: "https://alexandriacatolica.blogspot.com/2011/03/fonte-meditacoes-para-todos-os-dias-e.html",
    fonteUrl: "https://alexandriacatolica.blogspot.com/2011/03/fonte-meditacoes-para-todos-os-dias-e.html",
    hospedagem: "Alexandria Católica",
  },
  {
    id: "combate-espiritual",
    titulo: "O Combate Espiritual",
    autor: "Lorenzo Scupoli",
    categoria: "Espiritualidade",
    descricao: "Clássico da ascética cristã sobre o combate contra vícios e tentações, vivamente recomendado por São Francisco de Sales.",
    capa: "/images/biblioteca/combate-espiritual.jpg",
    downloadUrl: "https://alexandriacatolica.blogspot.com/2012/09/obra-favorita-e-vivamente-recomendada.html",
    fonteUrl: "https://alexandriacatolica.blogspot.com/2012/09/obra-favorita-e-vivamente-recomendada.html",
    hospedagem: "Alexandria Católica",
  },
  {
    id: "sete-dores-maria",
    titulo: "As Sete Dores de Maria Santíssima",
    autor: "Coletânea",
    categoria: "Mariologia",
    descricao: "Coletânea devocional dedicada às Sete Dores da Santíssima Virgem Maria.",
    capa: "/images/biblioteca/sete-dores-maria.jpg",
    downloadUrl: "https://alexandriacatolica.blogspot.com/2011/07/as-sete-dores-de-maria-santissima.html",
    fonteUrl: "https://alexandriacatolica.blogspot.com/2011/07/as-sete-dores-de-maria-santissima.html",
    hospedagem: "Alexandria Católica",
  },
  {
    id: "sao-miguel-compilacao",
    titulo: "São Miguel Arcanjo — Compilação de Textos",
    autor: "Diversos autores católicos",
    categoria: "Formação",
    santo: "São Miguel Arcanjo",
    descricao: "Compilação de textos espirituais e doutrinais sobre São Miguel, virtudes e combate espiritual.",
    capa: "/images/biblioteca/sao-miguel.jpg",
    downloadUrl: "https://alexandriacatolica.blogspot.com/2022/08/",
    fonteUrl: "https://alexandriacatolica.blogspot.com/2022/08/",
    hospedagem: "Alexandria Católica",
  },
  {
    id: "imitacao-de-cristo",
    titulo: "Imitação de Cristo",
    autor: "Tomás de Kempis",
    categoria: "Espiritualidade",
    descricao: "Um dos livros espirituais mais lidos na tradição católica, sobre humildade, vida interior e seguimento de Cristo.",
    capa: "/images/biblioteca/imitacao-de-cristo.jpg",
    downloadUrl: "https://alexandriacatolica.blogspot.com/search?q=Imita%C3%A7%C3%A3o+de+Cristo",
    fonteUrl: "https://alexandriacatolica.blogspot.com/search?q=Imita%C3%A7%C3%A3o+de+Cristo",
    hospedagem: "Alexandria Católica",
  },
  {
    id: "catecismo-sao-pio-x",
    titulo: "Catecismo Maior de São Pio X",
    autor: "Papa São Pio X",
    categoria: "Formação",
    descricao: "Exposição catequética clássica e clara dos principais pontos da fé e da moral católicas.",
    capa: "/images/biblioteca/catecismo-sao-pio-x.jpg",
    downloadUrl: "https://alexandriacatolica.blogspot.com/search?q=Catecismo+Maior+de+S%C3%A3o+Pio+X",
    fonteUrl: "https://alexandriacatolica.blogspot.com/search?q=Catecismo+Maior+de+S%C3%A3o+Pio+X",
    hospedagem: "Alexandria Católica",
  },
  {
    id: "preparacao-para-a-morte",
    titulo: "Preparação para a Morte",
    autor: "Santo Afonso Maria de Ligório",
    categoria: "Oração",
    descricao: "Reflexões sobre as últimas coisas, o amor de Deus e a necessidade de conversão e perseverança.",
    capa: "/images/biblioteca/preparacao-para-a-morte.jpg",
    downloadUrl: "https://alexandriacatolica.blogspot.com/search?q=Prepara%C3%A7%C3%A3o+para+a+Morte",
    fonteUrl: "https://alexandriacatolica.blogspot.com/search?q=Prepara%C3%A7%C3%A3o+para+a+Morte",
    hospedagem: "Alexandria Católica",
  },
  {
    id: "abandono-providencia-divina",
    titulo: "Abandono à Providência Divina",
    autor: "Jean-Pierre de Caussade",
    categoria: "Espiritualidade",
    descricao: "Clássico sobre confiança na Providência, santificação do momento presente e abandono filial a Deus.",
    capa: "/images/biblioteca/abandono-providencia.jpg",
    downloadUrl: "https://alexandriacatolica.blogspot.com/search?q=Abandono+%C3%A0+Provid%C3%AAncia+Divina",
    fonteUrl: "https://alexandriacatolica.blogspot.com/search?q=Abandono+%C3%A0+Provid%C3%AAncia+Divina",
    hospedagem: "Alexandria Católica",
  },
  {
    id: "segredo-admiravel-rosario",
    titulo: "O Segredo Admirável do Santíssimo Rosário",
    autor: "São Luís Maria Grignion de Montfort",
    categoria: "Mariologia",
    descricao: "Breve tratado mariano sobre a grandeza do Rosário e seu valor para a vida espiritual e apostólica.",
    capa: "/images/biblioteca/segredo-rosario.jpg",
    downloadUrl: "https://alexandriacatolica.blogspot.com/search?q=Segredo+Admir%C3%A1vel+do+Sant%C3%ADssimo+Ros%C3%A1rio",
    fonteUrl: "https://alexandriacatolica.blogspot.com/search?q=Segredo+Admir%C3%A1vel+do+Sant%C3%ADssimo+Ros%C3%A1rio",
    hospedagem: "Alexandria Católica",
  },
  {
    id: "paixao-nosso-senhor",
    titulo: "A Paixão de Nosso Senhor Jesus Cristo",
    autor: "Santo Afonso Maria de Ligório",
    categoria: "Espiritualidade",
    descricao: "Meditações sobre os sofrimentos redentores de Cristo, úteis especialmente para Quaresma e oração pessoal.",
    capa: "/images/biblioteca/paixao-nosso-senhor.jpg",
    downloadUrl: "https://alexandriacatolica.blogspot.com/search?q=A+Paix%C3%A3o+de+Nosso+Senhor+Jesus+Cristo",
    fonteUrl: "https://alexandriacatolica.blogspot.com/search?q=A+Paix%C3%A3o+de+Nosso+Senhor+Jesus+Cristo",
    hospedagem: "Alexandria Católica",
  },
  {
    id: "manual-do-coroinha",
    titulo: "Manual do Coroinha e do Acólito",
    autor: "Formação Católica",
    categoria: "Formação",
    descricao: "Material de apoio para o serviço do altar: postura, reverência, partes da missa e funções litúrgicas.",
    capa: "/images/biblioteca/manual-coroinha.jpg",
    downloadUrl: "https://alexandriacatolica.blogspot.com/search?q=coroinha+ac%C3%B3lito",
    fonteUrl: "https://alexandriacatolica.blogspot.com/search?q=coroinha+ac%C3%B3lito",
    hospedagem: "Alexandria Católica",
  },
]

export const categoriasBiblioteca = [
  "Todos",
  "Santos e Santas",
  "Espiritualidade",
  "Mariologia",
  "Oração",
  "Sacerdócio",
  "Formação",
] as const