export type PrefacioItem={id:string;titulo:string;documento:string}

function romano(s:string){return s.replace(/IX$/," IX").replace(/VIII$/," VIII").replace(/VII$/," VII").replace(/VI$/," VI").replace(/V$/," V").replace(/IV$/," IV").replace(/III$/," III").replace(/II$/," II").replace(/IA$/," I-A").replace(/IIA$/," II-A").replace(/I$/," I")}
function tituloBase(id:string){
 const especiais:Record<string,string>={NSAparecida:"Nossa Senhora Aparecida",anjos:"Anjos",anunciacao:"Anunciação do Senhor",apresentacao:"Apresentação do Senhor",arcanjos:"Arcanjos",ascensaodosenhor:"Ascensão do Senhor",batismo:"Batismo do Senhor",ceiadosenhor:"Ceia do Senhor",corpuschristi:"Corpus Christi",cristoreidouniverso:"Cristo Rei do Universo",epifania:"Epifania do Senhor",exaltacao:"Exaltação da Santa Cruz",paixaodosenhor:"Paixão do Senhor",pedroepaulo:"São Pedro e São Paulo",pentecostes:"Pentecostes",ramos:"Domingo de Ramos",sabadosanto:"Sábado Santo",santissimatrindade:"Santíssima Trindade",saojoao:"São João Batista",saojose:"São José",scj:"Sagrado Coração de Jesus",todosossantos:"Todos os Santos",transfiguracao:"Transfiguração do Senhor",crisma:"Crisma",enfermos:"Enfermos",martires:"Mártires",ordem:"Ordem",penitencia:"Penitência",santasvirgensreligiosos:"Santas Virgens e Religiosos",santospastores:"Santos Pastores"}
 if(especiais[id])return especiais[id]
 const m=id.match(/^(advento|apostolos|ascensao|comum|domingoTC|espiritosanto|fieisdefuntos|natal|paixao|pascoa|quaresma|santos|sseucaristia|virgemmaria)(.+)$/)
 if(!m)return id
 const nomes:Record<string,string>={advento:"Advento",apostolos:"Apóstolos",ascensao:"Ascensão",comum:"Comum",domingoTC:"Domingos do Tempo Comum",espiritosanto:"Espírito Santo",fieisdefuntos:"Fiéis Defuntos",natal:"Natal",paixao:"Paixão do Senhor",pascoa:"Páscoa",quaresma:"Quaresma",santos:"Santos",sseucaristia:"Santíssima Eucaristia",virgemmaria:"Virgem Maria"}
 return `${nomes[m[1]]} ${romano(m[2])}`
}
const proprios=["NSAparecida","anjos","anunciacao","apresentacao","arcanjos","ascensaodosenhor","batismo","ceiadosenhor","corpuschristi","cristoreidouniverso","epifania","exaltacao","paixaodosenhor","pedroepaulo","pentecostes","ramos","sabadosanto","santissimatrindade","saojoao","saojose","scj","todosossantos","transfiguracao"]
const tempo=["adventoI","adventoIA","adventoII","adventoIIA","anjos","apostolosI","apostolosII","ascensaoI","ascensaoII","batismo","comumI","comumII","comumIII","comumIV","comumV","comumVI","crisma","domingoTCI","domingoTCII","domingoTCIII","domingoTCIV","domingoTCIX","domingoTCV","domingoTCVI","domingoTCVII","domingoTCVIII","enfermos","espiritosantoI","espiritosantoII","fieisdefuntosI","fieisdefuntosII","fieisdefuntosIII","fieisdefuntosIV","fieisdefuntosV","martires","natalI","natalII","natalIII","ordem","paixaoI","paixaoII","pascoaI","pascoaII","pascoaIII","pascoaIV","pascoaV","penitencia","quaresmaI","quaresmaII","quaresmaIII","quaresmaIV","quaresmaV","santasvirgensreligiosos","santosI","santosII","santospastores","saojose","sseucaristiaI","sseucaristiaII","sseucaristiaIII","virgemmariaI","virgemmariaII"]
export const prefaciosProprios:PrefacioItem[]=proprios.map(id=>({id:`pp-${id}`,titulo:tituloBase(id),documento:`missal/prefacio/proprio/${id}.htm`}))
export const prefaciosTempo:PrefacioItem[]=tempo.map(id=>({id:`pt-${id}`,titulo:tituloBase(id),documento:`missal/prefacio/tempo/${id}.htm`}))
