import { inicioAdvento, pascoa, semanaTempoComum, tempoLiturgico } from "@/lib/iliturgia-calendario"

export type GrauLiturgico="solenidade"|"festa"|"memoria"|"memoria-facultativa"
export type CelebracaoLiturgica={nome:string;chave:string;grau:GrauLiturgico;imagem?:string}

const fixa:Record<string,CelebracaoLiturgica>={
 "01-01":{nome:"Santa Maria, Mãe de Deus",chave:"santamaria",grau:"solenidade"},"01-02":{nome:"São Basílio Magno e São Gregório Nazianzeno",chave:"basilioegregorio",grau:"memoria"},"01-03":{nome:"Santíssimo Nome de Jesus",chave:"ssnomedejesus",grau:"memoria-facultativa"},"01-07":{nome:"São Raimundo de Penaforte",chave:"",grau:"memoria-facultativa"},"01-13":{nome:"Santo Hilário",chave:"santohilario",grau:"memoria-facultativa"},"01-17":{nome:"Santo Antão",chave:"santoantao",grau:"memoria"},"01-20":{nome:"São Fabiano e São Sebastião",chave:"saofabiano",grau:"memoria-facultativa"},"01-21":{nome:"Santa Inês",chave:"santaines",grau:"memoria"},"01-22":{nome:"São Vicente",chave:"saovicente",grau:"memoria-facultativa"},"01-24":{nome:"São Francisco de Sales",chave:"saofranciscosales",grau:"memoria"},"01-25":{nome:"Conversão de São Paulo",chave:"conversaosaopaulo",grau:"festa"},"01-26":{nome:"São Timóteo e São Tito",chave:"saotimoteoetito",grau:"memoria"},"01-27":{nome:"Santa Ângela Mérici",chave:"angelamerici",grau:"memoria-facultativa"},"01-28":{nome:"Santo Tomás de Aquino",chave:"santotomas",grau:"memoria"},"01-31":{nome:"São João Bosco",chave:"saojoaobosco",grau:"memoria"},
 "02-02":{nome:"Apresentação do Senhor",chave:"apresentacao",grau:"festa"},"02-03":{nome:"São Brás",chave:"saobras",grau:"memoria-facultativa"},"02-05":{nome:"Santa Águeda",chave:"santaagueda",grau:"memoria"},"02-06":{nome:"São Paulo Miki e companheiros",chave:"saopaulomiki",grau:"memoria"},"02-08":{nome:"Santa Josefina Bakhita",chave:"josefinabakhita",grau:"memoria-facultativa"},"02-10":{nome:"Santa Escolástica",chave:"santaescolastica",grau:"memoria"},"02-11":{nome:"Nossa Senhora de Lourdes",chave:"NSLourdes",grau:"memoria-facultativa"},"02-14":{nome:"São Cirilo e São Metódio",chave:"saociriloemetodio",grau:"memoria"},"02-22":{nome:"Cátedra de São Pedro",chave:"catedra",grau:"festa"},"02-23":{nome:"São Policarpo",chave:"policarpo",grau:"memoria"},
 "03-04":{nome:"São Casimiro",chave:"saocasimiro",grau:"memoria-facultativa"},"03-07":{nome:"Santa Perpétua e Santa Felicidade",chave:"perpetuaefelicidade",grau:"memoria"},"03-08":{nome:"São João de Deus",chave:"joaodedeus",grau:"memoria-facultativa"},"03-09":{nome:"Santa Francisca Romana",chave:"franciscaromana",grau:"memoria-facultativa"},"03-17":{nome:"São Patrício",chave:"saopatricio",grau:"memoria-facultativa"},"03-18":{nome:"São Cirilo de Jerusalém",chave:"cirilojerusalem",grau:"memoria-facultativa"},"03-19":{nome:"São José, Esposo da Virgem Maria",chave:"saojose",grau:"solenidade"},"03-23":{nome:"São Turíbio de Mogrovejo",chave:"turibiodemogrovejo",grau:"memoria-facultativa"},"03-25":{nome:"Anunciação do Senhor",chave:"anunciacao",grau:"solenidade"},
 "04-02":{nome:"São Francisco de Paula",chave:"",grau:"memoria-facultativa"},"04-04":{nome:"Santo Isidoro",chave:"",grau:"memoria-facultativa"},"04-05":{nome:"São Vicente Ferrer",chave:"saovicenteferrer",grau:"memoria-facultativa"},"04-07":{nome:"São João Batista de La Salle",chave:"joaodelasalle",grau:"memoria"},"04-11":{nome:"Santo Estanislau",chave:"estanislau",grau:"memoria"},"04-13":{nome:"São Martinho I",chave:"martinhoI",grau:"memoria-facultativa"},"04-21":{nome:"Santo Anselmo",chave:"santoanselmo",grau:"memoria-facultativa"},"04-23":{nome:"São Jorge",chave:"saojorge",grau:"memoria-facultativa"},"04-24":{nome:"São Fidélis de Sigmaringa",chave:"",grau:"memoria-facultativa"},"04-25":{nome:"São Marcos, Evangelista",chave:"saomarcos",grau:"festa"},"04-28":{nome:"São Pedro Chanel",chave:"pedrochanel",grau:"memoria-facultativa"},"04-29":{nome:"Santa Catarina de Sena",chave:"santacatarina",grau:"memoria"},"04-30":{nome:"São Pio V",chave:"saopiov",grau:"memoria-facultativa"},
 "05-01":{nome:"São José Operário",chave:"saojoseoperario",grau:"memoria-facultativa"},"05-02":{nome:"Santo Atanásio",chave:"santoatanasio",grau:"memoria"},"05-03":{nome:"São Filipe e São Tiago",chave:"saofilipeetiago",grau:"festa"},"05-12":{nome:"São Nereu e Santo Aquiles",chave:"nereueaquiles",grau:"memoria-facultativa"},"05-13":{nome:"Nossa Senhora de Fátima",chave:"",grau:"memoria-facultativa"},"05-14":{nome:"São Matias",chave:"saomatias",grau:"festa"},"05-18":{nome:"São João I",chave:"joaoi",grau:"memoria-facultativa"},"05-20":{nome:"São Bernardino de Sena",chave:"saobernardino",grau:"memoria-facultativa"},"05-25":{nome:"São Beda Venerável",chave:"saobeda",grau:"memoria-facultativa"},"05-26":{nome:"São Filipe Néri",chave:"saofilipeneri",grau:"memoria"},"05-27":{nome:"Santo Agostinho de Cantuária",chave:"agostinhodecantuaria",grau:"memoria-facultativa"},"05-31":{nome:"Visitação de Nossa Senhora",chave:"visitacao",grau:"festa"},
 "06-01":{nome:"São Justino",chave:"saojustino",grau:"memoria"},"06-02":{nome:"São Marcelino e São Pedro",chave:"marcelinoepedro",grau:"memoria-facultativa"},"06-03":{nome:"São Carlos Lwanga e companheiros",chave:"saocarloslwanga",grau:"memoria"},"06-05":{nome:"São Bonifácio",chave:"saobonifacio",grau:"memoria"},"06-06":{nome:"São Norberto",chave:"norberto",grau:"memoria-facultativa"},"06-09":{nome:"São José de Anchieta",chave:"josedeanchieta",grau:"memoria"},"06-11":{nome:"São Barnabé",chave:"saobarnabe",grau:"memoria"},"06-13":{nome:"Santo Antônio de Pádua",chave:"santoantonio",grau:"memoria"},"06-19":{nome:"São Romualdo",chave:"saoromualdo",grau:"memoria-facultativa"},"06-21":{nome:"São Luís Gonzaga",chave:"saoluisgonzaga",grau:"memoria"},"06-22":{nome:"São Paulino de Nola; São João Fisher e São Tomás More",chave:"joaofishertomasmore",grau:"memoria-facultativa"},"06-24":{nome:"Natividade de São João Batista",chave:"natividade",grau:"solenidade"},"06-27":{nome:"São Cirilo de Alexandria",chave:"saociriloalexandria",grau:"memoria-facultativa"},"06-28":{nome:"Santo Irineu",chave:"santoirineu",grau:"memoria"},"06-29":{nome:"São Pedro e São Paulo",chave:"pedroepaulo",grau:"solenidade"},"06-30":{nome:"Protomártires da Igreja de Roma",chave:"protomartiresroma",grau:"memoria-facultativa"},
 "07-03":{nome:"São Tomé, Apóstolo",chave:"saotome",grau:"festa"},"07-04":{nome:"Santa Isabel de Portugal",chave:"isabeldeportugal",grau:"memoria-facultativa"},"07-06":{nome:"Santa Maria Goretti",chave:"mariagoretti",grau:"memoria-facultativa"},"07-09":{nome:"Santa Paulina",chave:"santapaulina",grau:"memoria"},"07-11":{nome:"São Bento",chave:"saobento",grau:"memoria"},"07-13":{nome:"Santo Henrique",chave:"santohenrique",grau:"memoria-facultativa"},"07-14":{nome:"São Camilo de Lellis",chave:"camilodelellis",grau:"memoria-facultativa"},"07-15":{nome:"São Boaventura",chave:"saoboaventura",grau:"memoria"},"07-16":{nome:"Nossa Senhora do Carmo",chave:"NSCarmo",grau:"memoria-facultativa"},"07-20":{nome:"Santo Inácio de Azevedo e companheiros",chave:"inaciodeazevedo",grau:"memoria"},"07-21":{nome:"São Lourenço de Brindisi",chave:"lourencodebrindisi",grau:"memoria-facultativa"},"07-22":{nome:"Santa Maria Madalena",chave:"stamariamadalena",grau:"festa"},"07-23":{nome:"Santa Brígida",chave:"santabrigida",grau:"memoria-facultativa"},"07-25":{nome:"São Tiago, Apóstolo",chave:"saotiago",grau:"festa"},"07-26":{nome:"São Joaquim e Santa Ana",chave:"saojoaquimesantana",grau:"memoria"},"07-29":{nome:"Santa Marta, Maria e Lázaro",chave:"santamarta",grau:"memoria"},"07-30":{nome:"São Pedro Crisólogo",chave:"saopedrocrisologo",grau:"memoria-facultativa"},"07-31":{nome:"Santo Inácio de Loyola",chave:"santoinacio",grau:"memoria"},
 "08-01":{nome:"Santo Afonso Maria de Ligório",chave:"santoafonso",grau:"memoria"},"08-04":{nome:"São João Maria Vianney",chave:"saojmvianney",grau:"memoria"},"08-05":{nome:"Dedicação da Basílica de Santa Maria Maior",chave:"santamariamaior",grau:"memoria-facultativa"},"08-06":{nome:"Transfiguração do Senhor",chave:"transfiguracao",grau:"festa"},"08-07":{nome:"São Sisto II e companheiros",chave:"saosisto",grau:"memoria-facultativa"},"08-08":{nome:"São Domingos",chave:"saodomingos",grau:"memoria"},"08-09":{nome:"Santa Teresa Benedita da Cruz",chave:"beneditadacruz",grau:"memoria-facultativa"},"08-10":{nome:"São Lourenço",chave:"saolourenco",grau:"festa"},"08-11":{nome:"Santa Clara",chave:"santaclara",grau:"memoria"},"08-12":{nome:"Santa Joana Francisca de Chantal",chave:"santajoanadechantal",grau:"memoria-facultativa"},"08-13":{nome:"São Ponciano e Santo Hipólito",chave:"saoponciano",grau:"memoria-facultativa"},"08-14":{nome:"São Maximiliano Maria Kolbe",chave:"saomaximiliano",grau:"memoria"},"08-15":{nome:"Assunção de Nossa Senhora",chave:"assuncao",grau:"solenidade"},"08-16":{nome:"Santo Estêvão da Hungria",chave:"estevaodahungria",grau:"memoria-facultativa"},"08-20":{nome:"São Bernardo",chave:"saobernardo",grau:"memoria"},"08-21":{nome:"São Pio X",chave:"saopiox",grau:"memoria"},"08-22":{nome:"Nossa Senhora Rainha",chave:"NSRainha",grau:"memoria"},"08-23":{nome:"Santa Rosa de Lima",chave:"santarosadelima",grau:"memoria"},"08-24":{nome:"São Bartolomeu, Apóstolo",chave:"saobartolomeu",grau:"festa"},"08-27":{nome:"Santa Mônica",chave:"santamonica",grau:"memoria"},"08-28":{nome:"Santo Agostinho",chave:"santoagostinho",grau:"memoria"},"08-29":{nome:"Martírio de São João Batista",chave:"joaobatista",grau:"memoria"},
 "09-03":{nome:"São Gregório Magno",chave:"saogregoriomagno",grau:"memoria"},"09-08":{nome:"Natividade de Nossa Senhora",chave:"natividadens",grau:"festa"},"09-09":{nome:"São Pedro Claver",chave:"pedroclaver",grau:"memoria-facultativa"},"09-13":{nome:"São João Crisóstomo",chave:"joaocrisostomo",grau:"memoria"},"09-14":{nome:"Exaltação da Santa Cruz",chave:"exaltacao",grau:"festa"},"09-15":{nome:"Nossa Senhora das Dores",chave:"NSDores",grau:"memoria"},"09-16":{nome:"São Cornélio e São Cipriano",chave:"cornelioecipriano",grau:"memoria"},"09-17":{nome:"São Roberto Belarmino",chave:"robertobelarmino",grau:"memoria-facultativa"},"09-19":{nome:"São Januário",chave:"saojanuario",grau:"memoria-facultativa"},"09-20":{nome:"Santos André Kim, Paulo Chong e companheiros",chave:"andrekim",grau:"memoria"},"09-21":{nome:"São Mateus, Apóstolo e Evangelista",chave:"saomateus",grau:"festa"},"09-23":{nome:"São Pio de Pietrelcina",chave:"padrepio",grau:"memoria"},"09-26":{nome:"São Cosme e São Damião",chave:"cosmeedamiao",grau:"memoria-facultativa"},"09-27":{nome:"São Vicente de Paulo",chave:"saovicentedepaulo",grau:"memoria"},"09-28":{nome:"São Venceslau",chave:"saovenceslau",grau:"memoria-facultativa"},"09-29":{nome:"Santos Arcanjos Miguel, Gabriel e Rafael",chave:"arcanjos",grau:"festa"},"09-30":{nome:"São Jerônimo",chave:"saojeronimo",grau:"memoria"},
 "10-01":{nome:"Santa Teresinha do Menino Jesus",chave:"stateresinha",grau:"memoria"},"10-02":{nome:"Santos Anjos da Guarda",chave:"anjos",grau:"memoria"},"10-04":{nome:"São Francisco de Assis",chave:"saofranciscodeassis",grau:"memoria"},"10-06":{nome:"São Bruno",chave:"saobruno",grau:"memoria-facultativa"},"10-07":{nome:"Nossa Senhora do Rosário",chave:"NSRosario",grau:"memoria"},"10-09":{nome:"São Dionísio e companheiros; São João Leonardi",chave:"",grau:"memoria-facultativa"},"10-11":{nome:"São João XXIII",chave:"saojoaoxxiii",grau:"memoria-facultativa"},"10-12":{nome:"Nossa Senhora Aparecida",chave:"NSAparecida",grau:"solenidade"},"10-14":{nome:"São Calisto I",chave:"saocalisto",grau:"memoria-facultativa"},"10-15":{nome:"Santa Teresa de Jesus",chave:"santateresadejesus",grau:"memoria"},"10-16":{nome:"Santa Edwiges; Santa Margarida Maria Alacoque",chave:"margaridamaria",grau:"memoria-facultativa"},"10-17":{nome:"Santo Inácio de Antioquia",chave:"inacioantioquia",grau:"memoria"},"10-18":{nome:"São Lucas, Evangelista",chave:"saolucas",grau:"festa"},"10-19":{nome:"São João de Brébeuf, Santo Isaac Jogues e companheiros",chave:"",grau:"memoria-facultativa"},"10-22":{nome:"São João Paulo II",chave:"saojoaopauloII",grau:"memoria-facultativa"},"10-23":{nome:"São João de Capistrano",chave:"joaocapistrano",grau:"memoria-facultativa"},"10-24":{nome:"Santo Antônio Maria Claret",chave:"antoniomariaclaret",grau:"memoria-facultativa"},"10-28":{nome:"São Simão e São Judas, Apóstolos",chave:"simaoejudas",grau:"festa"},
 "11-01":{nome:"Todos os Santos",chave:"todosossantos",grau:"solenidade"},"11-02":{nome:"Comemoração de Todos os Fiéis Defuntos",chave:"fieisdefuntos",grau:"solenidade"},"11-04":{nome:"São Carlos Borromeu",chave:"saocarlosborromeu",grau:"memoria"},"11-09":{nome:"Dedicação da Basílica do Latrão",chave:"latrao",grau:"festa"},"11-10":{nome:"São Leão Magno",chave:"saoleao",grau:"memoria"},"11-11":{nome:"São Martinho de Tours",chave:"saomartinho",grau:"memoria"},"11-12":{nome:"São Josafá",chave:"saojosafa",grau:"memoria"},"11-17":{nome:"Santa Isabel da Hungria",chave:"isabeldahungria",grau:"memoria"},"11-18":{nome:"Dedicação das Basílicas de São Pedro e São Paulo",chave:"basilicaspedroepaulo",grau:"memoria-facultativa"},"11-21":{nome:"Apresentação de Nossa Senhora",chave:"apresentacaoNS",grau:"memoria"},"11-22":{nome:"Santa Cecília",chave:"santacecilia",grau:"memoria"},"11-23":{nome:"São Clemente I",chave:"saoclemente",grau:"memoria-facultativa"},"11-24":{nome:"Santo André Dung-Lac e companheiros",chave:"santoandredung",grau:"memoria"},"11-25":{nome:"Santa Catarina de Alexandria",chave:"catarinadealexandria",grau:"memoria-facultativa"},"11-30":{nome:"Santo André, Apóstolo",chave:"santoandre",grau:"festa"},
 "12-03":{nome:"São Francisco Xavier",chave:"franciscoxavier",grau:"memoria"},"12-04":{nome:"São João Damasceno",chave:"joaodamasceno",grau:"memoria-facultativa"},"12-06":{nome:"São Nicolau",chave:"saonicolau",grau:"memoria-facultativa"},"12-07":{nome:"Santo Ambrósio",chave:"santoambrosio",grau:"memoria"},"12-08":{nome:"Imaculada Conceição de Nossa Senhora",chave:"imaculada",grau:"solenidade"},"12-09":{nome:"São João Diego",chave:"saojoaodiego",grau:"memoria-facultativa"},"12-10":{nome:"Nossa Senhora de Loreto",chave:"NSLoreto",grau:"memoria-facultativa"},"12-11":{nome:"São Dâmaso I",chave:"saodamaso",grau:"memoria-facultativa"},"12-12":{nome:"Nossa Senhora de Guadalupe",chave:"NSGuadalupe",grau:"memoria-facultativa"},"12-13":{nome:"Santa Luzia",chave:"santaluzia",grau:"memoria"},"12-14":{nome:"São João da Cruz",chave:"saojoaodacruz",grau:"memoria"},"12-21":{nome:"São Pedro Canísio",chave:"pedrocanisio",grau:"memoria-facultativa"},"12-23":{nome:"São João de Kenty",chave:"",grau:"memoria-facultativa"},"12-25":{nome:"Natal de Nosso Senhor Jesus Cristo",chave:"natal",grau:"solenidade"},"12-26":{nome:"Santo Estêvão, Primeiro Mártir",chave:"santoestevao",grau:"festa"},"12-27":{nome:"São João, Apóstolo e Evangelista",chave:"joaoevangelista",grau:"festa"},"12-28":{nome:"Santos Inocentes",chave:"santosinocentes",grau:"festa"},"12-29":{nome:"São Tomás Becket",chave:"tomasbecket",grau:"memoria-facultativa"},"12-31":{nome:"São Silvestre I",chave:"saosilvestre",grau:"memoria-facultativa"},
}

function add(d:Date,n:number){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function same(a:Date,b:Date){return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
function domingoEntre(ano:number,mes:number,d1:number,d2:number){for(let d=d1;d<=d2;d++){const x=new Date(ano,mes,d);if(x.getDay()===0)return x}return new Date(ano,mes,d1)}
function dias(a:Date,b:Date){const aa=Date.UTC(a.getFullYear(),a.getMonth(),a.getDate()),bb=Date.UTC(b.getFullYear(),b.getMonth(),b.getDate());return Math.floor((bb-aa)/86400000)}

export function celebracaoMovel(data:Date):CelebracaoLiturgica|null{
 const ano=data.getFullYear(),p=pascoa(ano),adv=inicioAdvento(ano)
 const epifania=domingoEntre(ano,0,2,8),batismo=add(epifania,epifania.getDate()===7||epifania.getDate()===8?1:7)
 const movimentos:[Date,CelebracaoLiturgica][]=[
  [epifania,{nome:"Epifania do Senhor",chave:"epifania",grau:"solenidade"}],[batismo,{nome:"Batismo do Senhor",chave:"batismo",grau:"festa"}],[add(p,-46),{nome:"Quarta-feira de Cinzas",chave:"cinzas",grau:"solenidade"}],[add(p,-7),{nome:"Domingo de Ramos e da Paixão do Senhor",chave:"ramos",grau:"solenidade"}],[add(p,-3),{nome:"Quinta-feira da Ceia do Senhor",chave:"ceiadosenhor",grau:"solenidade"}],[add(p,-2),{nome:"Sexta-feira da Paixão do Senhor",chave:"paixaodosenhor",grau:"solenidade"}],[add(p,-1),{nome:"Sábado Santo",chave:"sabadosanto",grau:"solenidade"}],[p,{nome:"Domingo da Páscoa na Ressurreição do Senhor",chave:"pascoa",grau:"solenidade"}],[add(p,7),{nome:"Domingo da Divina Misericórdia",chave:"divinamisericordia",grau:"solenidade"}],[add(p,42),{nome:"Ascensão do Senhor",chave:"ascensaodosenhor",grau:"solenidade"}],[add(p,49),{nome:"Pentecostes",chave:"pentecostes",grau:"solenidade"}],[add(p,50),{nome:"Bem-aventurada Virgem Maria, Mãe da Igreja",chave:"maedaigreja",grau:"memoria"}],[add(p,56),{nome:"Santíssima Trindade",chave:"santissimatrindade",grau:"solenidade"}],[add(p,60),{nome:"Santíssimo Corpo e Sangue de Cristo",chave:"corpuschristi",grau:"solenidade"}],[add(p,68),{nome:"Sagrado Coração de Jesus",chave:"scj",grau:"solenidade"}],[add(adv,-7),{nome:"Nosso Senhor Jesus Cristo, Rei do Universo",chave:"cristoreidouniverso",grau:"solenidade"}],
 ]
 for(const [d,c] of movimentos)if(same(data,d))return c
 if(data.getMonth()===11&&data.getDate()>=26&&data.getDate()<=31&&data.getDay()===0)return {nome:"Sagrada Família de Jesus, Maria e José",chave:"sagradafamilia",grau:"festa"}
 return null
}

function domingoTemporal(data:Date):CelebracaoLiturgica|null{
 if(data.getDay()!==0)return null
 const t=tempoLiturgico(data),ano=data.getFullYear(),p=pascoa(ano)
 if(t==="advento"){const n=Math.floor(dias(inicioAdvento(ano),data)/7)+1;return{nome:`${n}º Domingo do Advento`,chave:`${n}domingo`,grau:"solenidade"}}
 if(t==="quaresma"){const cinzas=add(p,-46),n=Math.max(1,Math.floor(dias(cinzas,data)/7)+1);return{nome:`${n}º Domingo da Quaresma`,chave:`${n}domingoquaresma`,grau:"solenidade"}}
 if(t==="pascoa"){const n=Math.floor(dias(p,data)/7)+1;return{nome:`${n}º Domingo da Páscoa`,chave:`${n}domingopascoa`,grau:"solenidade"}}
 if(t==="tempocomum"){const n=semanaTempoComum(data);return{nome:`${n}º Domingo do Tempo Comum`,chave:`${n}domingoTC`,grau:"festa"}}
 if(t==="natal")return{nome:"Domingo do Tempo do Natal",chave:"domingonatal",grau:"festa"}
 return null
}

function prioridade(g:GrauLiturgico){return g==="solenidade"?4:g==="festa"?3:g==="memoria"?2:1}
export function celebracaoDoDia(data:Date=new Date()):CelebracaoLiturgica|null{
 const movel=celebracaoMovel(data); if(movel)return movel
 const domingo=domingoTemporal(data)
 const k=`${String(data.getMonth()+1).padStart(2,"0")}-${String(data.getDate()).padStart(2,"0")}`,f=fixa[k]||null
 if(!domingo)return f
 if(!f)return domingo
 const t=tempoLiturgico(data)
 if(t==="advento"||t==="quaresma"||t==="pascoa")return domingo
 if(f.grau==="solenidade")return f
 return domingo
}

export function imagemCelebracao(c:CelebracaoLiturgica|null){return c?.imagem||(c?.chave?`/${c.chave}.jpg`:"")}
