"use strict";
(() => {
  const P = () => window.Capacitor?.Plugins?.OfflineStore;
  const parse = (v,f=null) => { try { return JSON.parse(v); } catch { return f; } };
  const id = () => `quiz-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
  const escapeHtml = (v) => String(v ?? "").replace(/[&<>"']/g, m => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
  async function read(key){try{const r=await P()?.loadDocument({key});return r?.value?parse(r.value):null;}catch{return null;}}
  async function queue(item){let list=[];try{const r=await P()?.loadQueue();list=parse(r?.queue||"[]",[]);if(!Array.isArray(list))list=[];}catch{}list.push(item);try{await P()?.saveQueue({queue:JSON.stringify(list)});}catch{}show("Respostas salvas no aparelho. Serão sincronizadas depois.");}
  function show(text){const e=document.createElement("div");e.className="toast";e.textContent=text;document.body.appendChild(e);setTimeout(()=>e.remove(),3400);}
  function modal(title,questions,submit){const wrap=document.createElement("div");wrap.className="nav-modal";wrap.innerHTML=`<div class="nav-panel"><div class="row between"><b style="color:var(--wine)">${escapeHtml(title)}</b><button class="icon-btn" type="button" data-close>×</button></div><form data-qform style="margin-top:12px">${questions.map((q,i)=>`<fieldset style="border:0;padding:0;margin:0 0 14px"><legend style="font-size:11px;font-weight:800;margin-bottom:7px">${i+1}. ${escapeHtml(q.enunciado)}</legend>${(q.opcoes||[]).map((o,j)=>`<label class="card row" style="padding:9px;margin:5px 0"><input required type="radio" name="q${i}" value="${j}"><span style="font-size:10px">${String.fromCharCode(65+j)}. ${escapeHtml(o)}</span></label>`).join("")}</fieldset>`).join("")}<button class="btn" type="submit">Salvar respostas</button></form></div>`;document.body.appendChild(wrap);wrap.querySelector("[data-close]").onclick=()=>wrap.remove();wrap.querySelector("[data-qform]").onsubmit=async ev=>{ev.preventDefault();const fd=new FormData(ev.currentTarget);const answers=questions.map((_,i)=>Number(fd.get(`q${i}`)));await submit(answers);wrap.remove();};}
  async function manual(quizId){const data=await read("local:quizzes");const q=(data?.quizzes||[]).find(x=>String(x.id)===String(quizId));if(!q){show("Quiz ainda não sincronizado neste aparelho.");return;}modal(q.titulo||"Quiz",q.perguntas||[],answers=>queue({id:id(),path:`/api/quizzes/${encodeURIComponent(q.id)}/responder`,method:"POST",body:JSON.stringify({respostas:answers}),contentType:"application/json; charset=utf-8",label:"Respostas do quiz",createdAt:Date.now(),attempts:0,acceptConflict:true}));}
  async function liturgia(){const data=await read("local:quiz-liturgia");const q=data?.quiz;if(!q){show("Quiz Litúrgico ainda não sincronizado neste aparelho.");return;}modal(q.titulo||"Quiz da Liturgia",q.perguntas||[],answers=>queue({id:id(),path:"/api/quizzes/liturgia/responder",method:"POST",body:JSON.stringify({token:q.token,respostas:answers}),contentType:"application/json; charset=utf-8",label:"Quiz Litúrgico",createdAt:Date.now(),attempts:0,acceptConflict:true}));}
  document.addEventListener("click",ev=>{const el=ev.target instanceof Element?ev.target.closest("[data-quiz],[data-action]"):null;if(!el)return;if(el.hasAttribute("data-quiz")){ev.preventDefault();ev.stopImmediatePropagation();void manual(el.getAttribute("data-quiz"));}else if(el.getAttribute("data-action")==="open-lit-quiz"){ev.preventDefault();ev.stopImmediatePropagation();void liturgia();}},true);
})();
